name: Android Test

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '18'
      
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
          
    - name: Create emulator
      run: |
          ls $ANDROID_HOME/cmdline-tools
          $.ANDROID_HOME/cmdline-tools/bin/sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.2"
          $.ANDROID_HOME/cmdline-tools/bin/avdmanager create avd -n test-emulator -k "system-images;android-30;google_apis;x86"
    - name: Debug cmdline-tools contents
      run: |
         ls -R $ANDROID_HOME/cmdline-tools
    - name: Launch emulator
      run: |
        emulator -avd test-emulator -no-audio -no-window -accel auto -gpu swiftshader

    - name: Wait for emulator to start
      run: |
        android-wait-for-emulator

    - name: Run Test Case
      run: |
        # Add your test execution command here
