name: Android Test

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '18'
      
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
          
    - name: Create emulator
      run: |
            sdkmanager tools platform-tools
            $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-30" "system-images;android-30;google_apis;x86" "build-tools;30.0.2"
            echo "no" | $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd -n Pixel_3a -k "system-images;android-30;google_apis;x86" --force
            echo "no" | $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd -n Pixel_6a -k "system-images;android-30;google_apis;x86" --force

    - name: Debug cmdline-tools contents
      run: |
         ls -R $ANDROID_HOME/cmdline-tools
    - name: Launch emulator
      run: |
        cd $HOME/android/sdk/emulator
        ./emulator -avd Pixel_3a -no-audio -no-window -accel auto -gpu swiftshader
        ./emulator -avd Pixel_6a -no-audio -no-window -accel auto -gpu swiftshader

    - name: Wait for emulator to start
      run: |
        android-wait-for-emulator

    - name: Run Test Case
      run: |
        # Add your test execution command here
